export const metadata = {
  users: [
    {
      id: "u1",
      fullname: "Arjun Sharma",
      email: "arjun@devhub.io",
      bio: "Full-stack dev, loves clean code.",
      avatar: "https://i.pravatar.cc/150?img=11",
      projectIds: ["proj1", "proj2"],
      createdBy: "system",
      updatedBy: "system",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "u2",
      fullname: "Priya Mehta",
      email: "priya@devhub.io",
      bio: "UI/UX designer & React dev.",
      avatar: "https://i.pravatar.cc/150?img=5",
      projectIds: ["proj1"],
      createdBy: "system",
      updatedBy: "system",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "u3",
      fullname: "Rohit Verma",
      email: "rohit@devhub.io",
      bio: "Backend engineer. Node & Postgres.",
      avatar: "https://i.pravatar.cc/150?img=8",
      projectIds: ["proj2"],
      createdBy: "system",
      updatedBy: "system",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "u4",
      fullname: "Sneha Kapoor",
      email: "sneha@devhub.io",
      bio: "QA automation & testing.",
      avatar: "https://i.pravatar.cc/150?img=47",
      projectIds: ["proj1", "proj2"],
      createdBy: "system",
      updatedBy: "system",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "u5",
      fullname: "Karthik Iyer",
      email: "karthik@devhub.io",
      bio: "DevOps & cloud infrastructure.",
      avatar: "https://i.pravatar.cc/150?img=15",
      projectIds: ["proj2"],
      createdBy: "system",
      updatedBy: "system",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
  ],
  projects: [
    {
      id: "proj1",
      title: "E-Commerce Platform Redesign",
      description:
        "A comprehensive end-to-end redesign and technical rebuild of the consumer-facing e-commerce storefront. This project encompasses a full audit of the existing user experience, identifying pain points across the product discovery, cart, and checkout flows, and addressing them through modern UI patterns, improved information architecture, and performance-optimized frontend engineering. The redesign introduces a new component-driven design system built with React and TypeScript, ensuring visual consistency and long-term scalability across all customer touchpoints. Key focus areas include mobile-first responsive layouts, accessibility compliance to WCAG 2.1 AA standards, integration with the updated REST and GraphQL APIs, and significant improvements to page load performance targeting a Lighthouse score of 90+ across all core pages. The project also involves rebuilding the product listing and filtering engine, redesigning the user account dashboard, and overhauling the multi-step checkout experience to reduce drop-off rates. Cross-functional collaboration with the backend, design, QA, and product teams is central to delivery.",
      memberIds: ["u1", "u2", "u4", "u5"],
      sectionIds: ["sec1", "sec2", "sec3", "sec4", "sec5"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "proj2",
      title: "Internal DevOps Dashboard",
      description:
        "Design and development of a real-time internal operations dashboard intended to give the engineering and infrastructure teams full visibility into system health, deployment pipelines, service uptime, and key performance metrics across all production and staging environments. The dashboard aggregates data from multiple sources including CI/CD pipeline events, cloud provider monitoring APIs, error tracking services, and custom internal telemetry streams, presenting them in a unified, role-aware interface. Built with React, TypeScript, and WebSocket-based live data feeds, the platform supports configurable widget layouts, threshold-based alerting with color-coded severity indicators, historical trend charts, and one-click drill-down into individual service logs and deployment histories. The project prioritizes low-latency data rendering, graceful degradation when upstream services are unavailable, and a clean, high-density UI optimized for large monitor setups typically used in operations centers. Access control is enforced at the team and role level, ensuring that engineers, managers, and stakeholders each see relevant data without exposing sensitive infrastructure details beyond their permissions.",
      memberIds: ["u1", "u3", "u4", "u5"],
      sectionIds: ["sec6", "sec7", "sec8", "sec9", "sec10"],
      createdBy: "u3",
      updatedBy: "u3",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
  ],

  workflows: [
    {
      id: "wf1",
      title: "Standard Kanban",
      description: "4-step kanban for general feature work.",
      workflowSteps: [
        {
          id: "wsA1",
          title: "Backlog",
          description: "Items not yet started",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsA2",
          title: "In Progress",
          description: "Actively being worked on",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsA3",
          title: "In Review",
          description: "Awaiting peer review",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsA4",
          title: "Done",
          description: "Completed & merged",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
      ],
      defaultWorkflowStep: {
        id: "wsA1",
        title: "Backlog",
        description: "Items not yet started",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "wf2",
      title: "Bug Triage Flow",
      description: "End-to-end bug tracking from report to close.",
      workflowSteps: [
        {
          id: "wsB1",
          title: "Reported",
          description: "Bug filed",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsB2",
          title: "Triaged",
          description: "Severity assessed",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsB3",
          title: "In Fix",
          description: "Dev assigned & fixing",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsB4",
          title: "Testing",
          description: "QA verification",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsB5",
          title: "Closed",
          description: "Verified & closed",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
      ],
      defaultWorkflowStep: {
        id: "wsB1",
        title: "Reported",
        description: "Bug filed",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "wf3",
      title: "Design Sprint",
      description: "Design process from ideation to ship.",
      workflowSteps: [
        {
          id: "wsC1",
          title: "Ideate",
          description: "Brainstorm & sketches",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsC2",
          title: "Design",
          description: "Hi-fi mockups",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsC3",
          title: "Handoff",
          description: "Specs handed to dev",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsC4",
          title: "Shipped",
          description: "Live in product",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
      ],
      defaultWorkflowStep: {
        id: "wsC1",
        title: "Ideate",
        description: "Brainstorm & sketches",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      createdBy: "u2",
      updatedBy: "u2",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "wf4",
      title: "Release Pipeline",
      description: "Multi-env release cycle with UAT gate.",
      workflowSteps: [
        {
          id: "wsD1",
          title: "Planned",
          description: "Scheduled for release",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsD2",
          title: "Development",
          description: "Feature in dev",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsD3",
          title: "Staging",
          description: "Deployed to staging",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsD4",
          title: "UAT",
          description: "User acceptance testing",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsD5",
          title: "Production",
          description: "Released to prod",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
      ],
      defaultWorkflowStep: {
        id: "wsD1",
        title: "Planned",
        description: "Scheduled for release",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "wf5",
      title: "Research Spike",
      description: "Short-cycle spike to validate an approach.",
      workflowSteps: [
        {
          id: "wsE1",
          title: "Proposed",
          description: "Spike proposed",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsE2",
          title: "Investigating",
          description: "Research in progress",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
        {
          id: "wsE3",
          title: "Documented",
          description: "Findings written up",
          createdBy: "u1",
          updatedBy: "u1",
          createdAt: "2025-01-15T09:00:00Z",
          updatedAt: "2025-01-15T09:00:00Z",
        },
      ],
      defaultWorkflowStep: {
        id: "wsE1",
        title: "Proposed",
        description: "Spike proposed",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      createdBy: "u3",
      updatedBy: "u3",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
  ],
  sections: [
    {
      id: "sec1",
      title: "UX Research & Design System",
      description:
        "Covers all user experience research, wireframing, prototyping, and design system deliverables for the platform redesign. This section tracks work from initial user interviews and heuristic evaluations through to high-fidelity Figma prototypes, component specification documents, and handoff-ready design assets. Includes tasks related to defining the visual language, typography scale, color tokens, spacing system, and interaction patterns that will be implemented across the frontend.",
      projectId: "proj1",
      storyCardIds: ["sc1", "sc2"],
      ticketIds: ["t1", "t2", "t3"],
      workflowId: "wf3",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec2",
      title: "Frontend Component Development",
      description:
        "Encompasses all React and TypeScript component development for the consumer-facing storefront. This section manages work related to building the design system component library, implementing page-level layouts, integrating API data layers using React Query, managing application state with Redux Toolkit, and ensuring all components meet accessibility standards. Tasks in this section follow a code review and storybook documentation requirement before being merged into the main branch.",
      projectId: "proj1",
      storyCardIds: ["sc3", "sc4"],
      ticketIds: ["t4", "t5", "t6", "t7"],
      workflowId: "wf1",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec3",
      title: "Bug Triage & Production Fixes",
      description:
        "Dedicated section for tracking all bugs reported through QA cycles, user feedback channels, and production monitoring alerts. Each ticket in this section is triaged by severity and assigned a priority level before being picked up for investigation. The workflow enforces a root-cause analysis comment before any fix is submitted for review, ensuring that recurring issues are documented and addressed at the systemic level rather than just the symptom level.",
      projectId: "proj1",
      storyCardIds: ["sc5"],
      ticketIds: ["t8", "t9", "t10"],
      workflowId: "wf2",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec4",
      title: "Performance Optimization & Profiling",
      description:
        "Tracks all performance-related investigations, profiling sessions, and optimization work across the frontend and API layers. This section includes tasks for improving Core Web Vitals scores, reducing JavaScript bundle sizes through code splitting and tree shaking, optimizing image delivery pipelines, implementing lazy loading strategies, and addressing render bottlenecks identified through React Profiler and Lighthouse audits. All tickets require before-and-after benchmark data to be attached before closing.",
      projectId: "proj1",
      storyCardIds: ["sc6"],
      ticketIds: ["t11", "t12", "t13"],
      workflowId: "wf5",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec5",
      title: "Release Coordination & Deployment Pipeline",
      description:
        "Manages all tasks related to versioning, release preparation, environment promotions, and production deployment coordination. This section covers changelog generation, feature flag configuration, smoke test sign-offs, rollback plan documentation, and communication with stakeholders ahead of each release window. CI/CD pipeline configuration changes and deployment script updates are also tracked here to ensure deployment processes remain reliable and auditable.",
      projectId: "proj1",
      storyCardIds: ["sc7"],
      ticketIds: ["t14", "t15", "t16"],
      workflowId: "wf4",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec6",
      title: "Discovery, Spikes & Stakeholder Research",
      description:
        "Houses all exploratory work, technical spike investigations, and stakeholder alignment tasks that precede active development. This section is used to evaluate third-party integrations, assess technical feasibility of proposed features, document architectural decision records, and gather requirements through interviews and workshops. Tickets here are time-boxed and expected to produce a written summary or proof-of-concept before being closed or promoted into a development section.",
      projectId: "proj2",
      storyCardIds: ["sc8"],
      ticketIds: ["t17", "t18"],
      workflowId: "wf5",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec7",
      title: "Reusable UI Component Library",
      description:
        "Dedicated to the design and development of the reusable React component library that powers the internal DevOps dashboard. Components built in this section include data tables with sorting and filtering, real-time metric cards, status badge systems, configurable chart wrappers, timeline visualizers, and notification panels. All components are built with TypeScript, documented in Storybook, and tested with React Testing Library to ensure reliability and ease of reuse across different dashboard views.",
      projectId: "proj2",
      storyCardIds: ["sc9", "sc10"],
      ticketIds: ["t19", "t20", "t21", "t22"],
      workflowId: "wf1",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec8",
      title: "NestJS Backend API & Data Integration",
      description:
        "Covers all backend development work for the NestJS API layer that serves the DevOps dashboard. This includes building RESTful endpoints for service health data, integrating with third-party monitoring APIs such as Datadog, PagerDuty, and GitHub Actions, implementing WebSocket gateways for real-time data streaming, setting up role-based access control guards, writing database migration scripts, and ensuring all API responses are properly typed, validated using class-validator, and covered by integration tests.",
      projectId: "proj2",
      storyCardIds: ["sc11"],
      ticketIds: ["t23", "t24", "t25", "t26", "t27"],
      workflowId: "wf1",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec9",
      title: "QA, Testing & Coverage Improvement",
      description:
        "Manages all quality assurance activities including manual test case execution, automated test authoring, regression testing, and coverage gap analysis. This section tracks work for writing unit tests with Jest, integration tests with Supertest, end-to-end tests with Cypress, and accessibility audits using axe-core. Any ticket that introduces a new feature or modifies existing behavior is required to have a corresponding test ticket linked in this section before the feature is eligible for production release.",
      projectId: "proj2",
      storyCardIds: ["sc12"],
      ticketIds: ["t28", "t29", "t30"],
      workflowId: "wf2",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sec10",
      title: "Production Release & Readiness Checklist",
      description:
        "Coordinates all tasks required to prepare the DevOps dashboard for production deployment and ongoing operational readiness. This section includes environment variable audits, secrets rotation, infrastructure provisioning scripts, load testing sign-offs, monitoring and alerting configuration, runbook documentation, and final stakeholder demo sign-offs. Each release in this section follows a structured readiness checklist that must be fully completed and approved by both the engineering lead and product owner before any production promotion is initiated.",
      projectId: "proj2",
      storyCardIds: ["sc13"],
      ticketIds: ["t31", "t32", "t33"],
      workflowId: "wf4",
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
  ],

  storyCards: [
    {
      id: "sc1",
      title: "Homepage Redesign",
      description: "Redesign the hero section and navigation bar",
      assignedTo: "u2",
      storyPoints: 8,
      priority: "high",
      workflowStep: {
        id: "wsC2",
        title: "Design",
        description: "Hi-fi mockups",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf3",
      projectId: "proj1",
      sectionId: "sec1",
      ticketIds: ["t1", "t2"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc2",
      title: "Product Page Revamp",
      description: "New product detail layout with media gallery",
      assignedTo: "u2",
      storyPoints: 5,
      priority: "medium",
      workflowStep: {
        id: "wsC1",
        title: "Ideate",
        description: "Brainstorm & sketches",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf3",
      projectId: "proj1",
      sectionId: "sec1",
      ticketIds: ["t3"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc3",
      title: "Cart & Checkout Flow",
      description: "Rebuild cart sidebar and multi-step checkout",
      assignedTo: "u1",
      storyPoints: 13,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj1",
      sectionId: "sec2",
      ticketIds: ["t4", "t5", "t6"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc4",
      title: "Search & Filter UI",
      description: "Faceted search bar with real-time filtering",
      assignedTo: "u1",
      storyPoints: 8,
      priority: "medium",
      workflowStep: {
        id: "wsA1",
        title: "Backlog",
        description: "Items not yet started",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj1",
      sectionId: "sec2",
      ticketIds: ["t7"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc5",
      title: "Checkout Bugs Sprint",
      description: "Critical bugs blocking checkout completion",
      assignedTo: "u4",
      storyPoints: 5,
      priority: "high",
      workflowStep: {
        id: "wsB3",
        title: "In Fix",
        description: "Dev assigned & fixing",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj1",
      sectionId: "sec3",
      ticketIds: ["t8", "t9"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc6",
      title: "Image Optimization Spike",
      description: "Research next-gen image formats & lazy loading",
      assignedTo: "u3",
      storyPoints: 5,
      priority: "medium",
      workflowStep: {
        id: "wsE2",
        title: "Investigating",
        description: "Research in progress",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj1",
      sectionId: "sec4",
      ticketIds: ["t11", "t12"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc7",
      title: "v2.0 Release",
      description: "Full release of the redesigned e-commerce platform",
      assignedTo: "u5",
      storyPoints: 8,
      priority: "high",
      workflowStep: {
        id: "wsD3",
        title: "Staging",
        description: "Deployed to staging",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj1",
      sectionId: "sec5",
      ticketIds: ["t14", "t15"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc8",
      title: "Infra Metrics Spike",
      description: "Determine which infra metrics to surface in the dashboard",
      assignedTo: "u5",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsE2",
        title: "Investigating",
        description: "Research in progress",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj2",
      sectionId: "sec6",
      ticketIds: ["t17", "t18"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc9",
      title: "Metrics Chart Library",
      description: "Build reusable chart components (line, bar, gauge)",
      assignedTo: "u1",
      storyPoints: 13,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec7",
      ticketIds: ["t19", "t20", "t21"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc10",
      title: "Alert Feed Component",
      description: "Real-time alert feed with severity color coding",
      assignedTo: "u1",
      storyPoints: 8,
      priority: "medium",
      workflowStep: {
        id: "wsA1",
        title: "Backlog",
        description: "Items not yet started",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec7",
      ticketIds: ["t22"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc11",
      title: "Metrics API",
      description: "NestJS endpoints for metrics aggregation",
      assignedTo: "u3",
      storyPoints: 13,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec8",
      ticketIds: ["t23", "t24", "t25"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc12",
      title: "Dashboard QA Sprint",
      description: "End-to-end QA of dashboard flows",
      assignedTo: "u4",
      storyPoints: 8,
      priority: "high",
      workflowStep: {
        id: "wsB3",
        title: "In Fix",
        description: "Dev assigned & fixing",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj2",
      sectionId: "sec9",
      ticketIds: ["t28", "t29"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "sc13",
      title: "Dashboard v1 Release",
      description: "Initial production release of the DevOps dashboard",
      assignedTo: "u5",
      storyPoints: 8,
      priority: "high",
      workflowStep: {
        id: "wsD2",
        title: "Development",
        description: "Feature in dev",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj2",
      sectionId: "sec10",
      ticketIds: ["t31", "t32"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
  ],
  tickets: [
    {
      id: "t1",
      title: "Create wireframes for homepage",
      description: "Low-fidelity wireframes for desktop and mobile",
      assignedTo: "u2",
      storyPoints: 2,
      priority: "medium",
      workflowStep: {
        id: "wsC2",
        title: "Design",
        description: "Hi-fi mockups",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf3",
      projectId: "proj1",
      sectionId: "sec1",
      storyCardId: "sc1",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t2",
      title: "Design hi-fi mockups",
      description: "Figma hi-fi designs with tokens applied",
      assignedTo: "u2",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsC3",
        title: "Handoff",
        description: "Specs handed to dev",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf3",
      projectId: "proj1",
      sectionId: "sec1",
      storyCardId: "sc1",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t3",
      title: "Product image carousel component",
      description: "Accessible image carousel with zoom",
      assignedTo: "u2",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsC1",
        title: "Ideate",
        description: "Brainstorm & sketches",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf3",
      projectId: "proj1",
      sectionId: "sec1",
      storyCardId: "sc2",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t4",
      title: "CartContext with React Query",
      description: "Persist cart state via React Query + API",
      assignedTo: "u1",
      storyPoints: 5,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj1",
      sectionId: "sec2",
      storyCardId: "sc3",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t5",
      title: "Checkout step components",
      description: "AddressStep, PaymentStep, ConfirmStep",
      assignedTo: "u2",
      storyPoints: 5,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj1",
      sectionId: "sec2",
      storyCardId: "sc3",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t6",
      title: "Order summary sidebar",
      description: "Sticky order summary component",
      assignedTo: "u1",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsA3",
        title: "In Review",
        description: "Awaiting peer review",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj1",
      sectionId: "sec2",
      storyCardId: "sc3",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t7",
      title: "Filter panel component",
      description: "Accordion filter panel with URL state sync",
      assignedTo: "u1",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsA1",
        title: "Backlog",
        description: "Items not yet started",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj1",
      sectionId: "sec2",
      storyCardId: "sc4",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t8",
      title: "Fix price rounding error",
      description: "Prices display incorrectly with tax applied",
      assignedTo: "u3",
      storyPoints: 2,
      priority: "critical",
      workflowStep: {
        id: "wsB3",
        title: "In Fix",
        description: "Dev assigned & fixing",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj1",
      sectionId: "sec3",
      storyCardId: "sc5",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t9",
      title: "Mobile cart drawer overflow",
      description: "Cart drawer extends past viewport on iPhone",
      assignedTo: "u1",
      storyPoints: 1,
      priority: "high",
      workflowStep: {
        id: "wsB4",
        title: "Testing",
        description: "QA verification",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj1",
      sectionId: "sec3",
      storyCardId: "sc5",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t10",
      title: "Coupon code not applying",
      description: "Discount code silently fails on some SKUs",
      assignedTo: "u4",
      storyPoints: 2,
      priority: "high",
      workflowStep: {
        id: "wsB2",
        title: "Triaged",
        description: "Severity assessed",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj1",
      sectionId: "sec3",
      storyCardId: null,
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t11",
      title: "Benchmark WebP vs AVIF",
      description: "Compare compression ratios across product images",
      assignedTo: "u3",
      storyPoints: 2,
      priority: "low",
      workflowStep: {
        id: "wsE2",
        title: "Investigating",
        description: "Research in progress",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj1",
      sectionId: "sec4",
      storyCardId: "sc6",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t12",
      title: "Implement lazy loading strategy",
      description: "Intersection Observer for below-fold images",
      assignedTo: "u1",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsE3",
        title: "Documented",
        description: "Findings written up",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj1",
      sectionId: "sec4",
      storyCardId: "sc6",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t13",
      title: "Bundle size analysis",
      description: "Identify large chunks with webpack-bundle-analyzer",
      assignedTo: "u1",
      storyPoints: 1,
      priority: "low",
      workflowStep: {
        id: "wsE1",
        title: "Proposed",
        description: "Spike proposed",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj1",
      sectionId: "sec4",
      storyCardId: null,
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t14",
      title: "Deploy to staging",
      description: "Build Docker image and deploy to staging cluster",
      assignedTo: "u5",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsD3",
        title: "Staging",
        description: "Deployed to staging",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj1",
      sectionId: "sec5",
      storyCardId: "sc7",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t15",
      title: "Smoke test on staging",
      description: "Run E2E test suite on staging environment",
      assignedTo: "u4",
      storyPoints: 2,
      priority: "high",
      workflowStep: {
        id: "wsD4",
        title: "UAT",
        description: "User acceptance testing",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj1",
      sectionId: "sec5",
      storyCardId: "sc7",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t16",
      title: "Production cutover",
      description: "Blue-green deploy and DNS switch",
      assignedTo: "u5",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsD1",
        title: "Planned",
        description: "Scheduled for release",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj1",
      sectionId: "sec5",
      storyCardId: null,
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t17",
      title: "Audit existing Datadog dashboards",
      description: "Catalogue all current panels and queries",
      assignedTo: "u5",
      storyPoints: 2,
      priority: "low",
      workflowStep: {
        id: "wsE2",
        title: "Investigating",
        description: "Research in progress",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj2",
      sectionId: "sec6",
      storyCardId: "sc8",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t18",
      title: "Stakeholder interviews",
      description: "Gather dev & ops requirements for key metrics",
      assignedTo: "u3",
      storyPoints: 1,
      priority: "low",
      workflowStep: {
        id: "wsE3",
        title: "Documented",
        description: "Findings written up",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf5",
      projectId: "proj2",
      sectionId: "sec6",
      storyCardId: "sc8",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t19",
      title: "LineChart with Recharts",
      description: "Responsive line chart for CPU/memory trends",
      assignedTo: "u1",
      storyPoints: 5,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec7",
      storyCardId: "sc9",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t20",
      title: "GaugeChart component",
      description: "Semicircular gauge for health score",
      assignedTo: "u2",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsA3",
        title: "In Review",
        description: "Awaiting peer review",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec7",
      storyCardId: "sc9",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t21",
      title: "BarChart for deploy frequency",
      description: "Grouped bar chart, grouped by service",
      assignedTo: "u1",
      storyPoints: 3,
      priority: "medium",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec7",
      storyCardId: "sc9",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t22",
      title: "WebSocket alert hook",
      description: "useAlertFeed hook consuming WS events",
      assignedTo: "u3",
      storyPoints: 5,
      priority: "high",
      workflowStep: {
        id: "wsA1",
        title: "Backlog",
        description: "Items not yet started",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec7",
      storyCardId: "sc10",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t23",
      title: "GET /metrics/cpu endpoint",
      description: "Returns CPU timeseries per service",
      assignedTo: "u3",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec8",
      storyCardId: "sc11",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t24",
      title: "GET /metrics/deploy-frequency",
      description: "Aggregates deploy events by service",
      assignedTo: "u3",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec8",
      storyCardId: "sc11",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t25",
      title: "Metrics caching layer",
      description: "Redis caching with 60s TTL for expensive queries",
      assignedTo: "u3",
      storyPoints: 5,
      priority: "medium",
      workflowStep: {
        id: "wsA1",
        title: "Backlog",
        description: "Items not yet started",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec8",
      storyCardId: "sc11",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t26",
      title: "Auth middleware",
      description: "JWT validation + RBAC for API routes",
      assignedTo: "u3",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsA3",
        title: "In Review",
        description: "Awaiting peer review",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec8",
      storyCardId: null,
      parentTicketId: null,
      subTicketIds: ["t27"],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t27",
      title: "Role guard for admin routes",
      description: "Guard restricting /admin/* to role=admin",
      assignedTo: "u3",
      storyPoints: 2,
      priority: "high",
      workflowStep: {
        id: "wsA2",
        title: "In Progress",
        description: "Actively being worked on",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf1",
      projectId: "proj2",
      sectionId: "sec8",
      storyCardId: null,
      parentTicketId: "t26",
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t28",
      title: "Chart render lag on Safari",
      description: "Charts take >3s to render on Safari 16",
      assignedTo: "u1",
      storyPoints: 2,
      priority: "high",
      workflowStep: {
        id: "wsB3",
        title: "In Fix",
        description: "Dev assigned & fixing",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj2",
      sectionId: "sec9",
      storyCardId: "sc12",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t29",
      title: "Alert feed drops messages",
      description: "WS events occasionally silently dropped",
      assignedTo: "u3",
      storyPoints: 3,
      priority: "critical",
      workflowStep: {
        id: "wsB2",
        title: "Triaged",
        description: "Severity assessed",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj2",
      sectionId: "sec9",
      storyCardId: "sc12",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t30",
      title: "Write E2E tests with Playwright",
      description: "Cover login, dashboard load, alert interaction",
      assignedTo: "u4",
      storyPoints: 5,
      priority: "medium",
      workflowStep: {
        id: "wsB1",
        title: "Reported",
        description: "Bug filed",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf2",
      projectId: "proj2",
      sectionId: "sec9",
      storyCardId: null,
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t31",
      title: "Provision Kubernetes namespace",
      description: "Create k8s namespace and resource quotas",
      assignedTo: "u5",
      storyPoints: 3,
      priority: "high",
      workflowStep: {
        id: "wsD2",
        title: "Development",
        description: "Feature in dev",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj2",
      sectionId: "sec10",
      storyCardId: "sc13",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t32",
      title: "Configure CI/CD pipeline",
      description: "GitHub Actions workflow for build+deploy",
      assignedTo: "u5",
      storyPoints: 5,
      priority: "high",
      workflowStep: {
        id: "wsD2",
        title: "Development",
        description: "Feature in dev",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj2",
      sectionId: "sec10",
      storyCardId: "sc13",
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
    {
      id: "t33",
      title: "Post-deploy monitoring",
      description: "Set up Datadog alerts for error rate & latency",
      assignedTo: "u5",
      storyPoints: 2,
      priority: "medium",
      workflowStep: {
        id: "wsD1",
        title: "Planned",
        description: "Scheduled for release",
        createdBy: "u1",
        updatedBy: "u1",
        createdAt: "2025-01-15T09:00:00Z",
        updatedAt: "2025-01-15T09:00:00Z",
      },
      workflowId: "wf4",
      projectId: "proj2",
      sectionId: "sec10",
      storyCardId: null,
      parentTicketId: null,
      subTicketIds: [],
      createdBy: "u1",
      updatedBy: "u1",
      createdAt: "2025-01-15T09:00:00Z",
      updatedAt: "2025-01-15T09:00:00Z",
    },
  ],
};
