import type { Education, User, WorkExperience } from "../types/users.type";

// Note: Remove the type annotations (": User[]", etc.) if running directly in Node.js
export const MOCK_USERS: User[] = [
  {
    id: 1,
    username: "alex_dev",
    fullName: "Alex Rivera",
    email: "alex@dev.com",
    password: "hash",
    bio: "Backend developer specializing in distributed systems, high-performance APIs, and optimizing complex database queries for modern cloud environments.",
    about:
      "Alex focuses on architecting robust server-side solutions using Node.js and NestJS. With extensive experience in cloud-native tooling, he implements scalable microservices and ensures seamless API integration across platforms. He is committed to writing clean, maintainable code and mentoring junior developers to foster collaboration. Outside of work, Alex enjoys contributing to open-source projects and exploring emerging backend technologies to stay ahead in the field.",
    skills:
      "NestJS, Supabase, PostgreSQL, JWT Authentication, Node.js, Express, TypeScript, REST APIs, Docker, CI/CD",
    profileImageUrl: "https://example.com/alex.jpg",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    username: "beatrice_j",
    fullName: "Beatrice Jordan",
    email: "b.jordan@design.com",
    password: "hash",
    bio: "Creative design lead crafting intuitive product experiences and bridging the gap between user needs and elegant visual solutions.",
    about:
      "Beatrice is an expert in developing comprehensive design systems and executing rapid prototyping to bring digital products to life. She leads cross-functional teams to ensure every visual element aligns with core brand values and accessibility standards. Her strategic approach involves deep user research, wireframing, and iterative testing. Beatrice believes that great design is not just about aesthetics but also about how effectively it functions.",
    skills:
      "Figma, Sketch, Adobe XD, Tailwind CSS, Design Systems, Wireframing, Prototyping, User Research, Accessibility, Responsive Design",
    profileImageUrl: "https://example.com/beatrice.jpg",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: 3,
    username: "charlie_data",
    fullName: "Charlie Smith",
    email: "charlie@data.io",
    password: "hash",
    bio: "Data architect building reliable analytics stacks and managing complex pipelines for enterprises leveraging information for strategic growth.",
    about:
      "Charlie works with modern data warehouses and machine learning tooling to extract actionable insights from massive datasets. He has a proven track record of designing scalable architectures that handle petabytes of data efficiently. By implementing automated validation and transformation processes, Charlie ensures high data integrity for business intelligence teams. He is constantly researching the latest trends in artificial intelligence to improve predictive modeling and analysis.",
    skills:
      "Python, SQL, Apache Airflow, Snowflake, dbt, Tableau, Power BI, Machine Learning, ETL Pipelines, BigQuery",
    profileImageUrl: "https://example.com/charlie.jpg",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-03T00:00:00Z",
  },
  {
    id: 4,
    username: "dana_ops",
    fullName: "Dana White",
    email: "dana@cloud.com",
    password: "hash",
    bio: "Cloud and DevOps engineer focused on infrastructure reliability, automation, and streamlining continuous deployment workflows for software teams.",
    about:
      "Dana helps organizations migrate legacy systems and operate efficiently on modern cloud platforms like AWS and Azure. Her expertise includes container orchestration with Kubernetes, infrastructure as code using Terraform, and building robust CI/CD pipelines. She prioritizes security and performance monitoring to maintain high availability for critical services. Dana is passionate about DevOps culture and works closely with developers to improve the software delivery lifecycle.",
    skills:
      "AWS, Kubernetes, Terraform, Jenkins, GitHub Actions, Docker, Prometheus, Grafana, Helm, ArgoCD",
    profileImageUrl: "https://example.com/dana.jpg",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T00:00:00Z",
  },
];

export const MOCK_WORK: WorkExperience[] = [
  {
    id: 1,
    userId: 1,
    username: "alex_dev",
    company: "Google",
    position: "Senior Engineer",
    location: "Mountain View, CA",
    startDate: "2022-01-01",
    description:
      "Leading the specialized cloud infrastructure management team focused on optimizing global server-side performance for high-traffic distributed systems. My daily responsibilities involve architecting resilient microservices, conducting deep-dive performance bottlenecks analysis, and implementing sophisticated caching strategies. I collaborate closely with cross-functional engineering leads to ensure seamless integration of new features while maintaining high availability and strict security protocols across all production environments.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    userId: 1,
    username: "alex_dev",
    company: "Meta",
    position: "Software Engineer",
    location: "Menlo Park, CA",
    startDate: "2020-01-01",
    endDate: "2021-12-31",
    description:
      "Dedicated core contributor to the React internal framework team where I focused primarily on developing concurrent mode features and enhancing the developer experience through better tooling. I was responsible for maintaining foundational libraries used by thousands of internal developers, performing rigorous code reviews, and drafting technical documentation for complex architectural changes. My work directly improved application startup times and reduced memory overhead for the main social networking platform and mobile web views.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    userId: 1,
    username: "alex_dev",
    company: "Startup X",
    position: "Junior Dev",
    location: "Remote",
    startDate: "2018-05-01",
    endDate: "2019-12-31",
    description:
      "Operated as a versatile fullstack developer within a fast-paced environment to build rapid minimum viable products for various early-stage venture capital projects. I gained extensive experience across the entire development lifecycle, from initial database schema design to frontend deployment using modern JavaScript frameworks. I played a key role in implementing responsive user interfaces and integrating third-party payment gateways while ensuring the code remained maintainable and scalable during rapid growth phases.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    userId: 2,
    username: "beatrice_j",
    company: "Adobe",
    position: "Design Lead",
    location: "San Jose, CA",
    startDate: "2021-06-01",
    description:
      "Currently serving as the Design Lead for the Creative Cloud suite, where I architect scalable UI design systems and supervise multi-disciplinary creative teams. I focus on bridging the gap between artistic vision and technical feasibility, ensuring that every design token and component is accessible and performant. My role involves high-level strategy, stakeholder management, and the constant refinement of internal design workflows to improve speed-to-market for major product updates and feature releases.",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: 5,
    userId: 2,
    username: "beatrice_j",
    company: "Canva",
    position: "Product Designer",
    location: "Sydney, Australia",
    startDate: "2019-01-01",
    endDate: "2021-05-30",
    description:
      "Conducted extensive qualitative and quantitative user research to identify pain points within the core editing experience, eventually leading to a complete overhaul of the navigation system. I worked in tight-knit sprints with engineers to execute rapid prototyping and iterative usability testing sessions. My designs focused on democratizing complex graphic design tools, making them intuitive for non-professional users while maintaining the power and flexibility required for more advanced creative projects.",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: 6,
    userId: 2,
    username: "beatrice_j",
    company: "Figma",
    position: "Design Intern",
    location: "San Francisco, CA",
    startDate: "2018-01-01",
    endDate: "2018-12-31",
    description:
      "Supported the core product team in developing foundational vector manipulation tools and expanding the internal component library for the Figma web application. I was responsible for creating detailed icon sets, testing early-stage prototyping features, and gathering feedback from the community beta programs. This role provided deep insights into collaborative design software architecture and the importance of maintaining high-fidelity rendering performance across various browser engines and operating systems.",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: 7,
    userId: 3,
    username: "charlie_data",
    company: "Snowflake",
    position: "Data Architect",
    location: "Bozeman, MT",
    startDate: "2022-01-01",
    description:
      "Designing comprehensive end-to-end ETL pipelines and managing large-scale data warehousing solutions for high-profile enterprise clients. I am responsible for defining data governance standards, optimizing SQL query performance for massive datasets, and ensuring the seamless flow of information between disparate cloud storage providers. My work enables business intelligence teams to derive real-time insights from complex data structures, ultimately driving strategic decision-making and operational efficiency across multiple global business units.",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-03T00:00:00Z",
  },
  {
    id: 8,
    userId: 3,
    username: "charlie_data",
    company: "Databricks",
    position: "Data Analyst",
    location: "San Francisco, CA",
    startDate: "2019-01-01",
    endDate: "2021-12-31",
    description:
      "Focused on statistical modeling and predictive analytics to help internal product teams understand user engagement patterns and feature adoption rates. I utilized Apache Spark for large-scale data processing and built automated reporting dashboards that visualized key performance indicators for executive stakeholders. My analysis directly influenced the development roadmap for collaborative notebook features and helped identify significant opportunities for improving the overall machine learning lifecycle management platform.",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-03T00:00:00Z",
  },
  {
    id: 9,
    userId: 4,
    username: "dana_ops",
    company: "AWS",
    position: "Solutions Architect",
    location: "Seattle, WA",
    startDate: "2021-01-01",
    description:
      "Leading technical consultations for Fortune 500 companies to facilitate large-scale cloud migrations and the implementation of modern serverless architectures. I design highly available, fault-tolerant systems using a variety of Amazon Web Services, focusing on cost optimization and security best practices. My role involves drafting detailed technical proposals, conducting hands-on workshops for client engineering teams, and troubleshooting complex networking issues to ensure a smooth transition from legacy on-premise infrastructure to the cloud.",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T00:00:00Z",
  },
  {
    id: 10,
    userId: 4,
    username: "dana_ops",
    company: "DigitalOcean",
    position: "Site Reliability Engineer",
    location: "New York, NY",
    startDate: "2018-01-01",
    endDate: "2020-12-31",
    description:
      "Maintained the operational health and 99.9% uptime for managed Kubernetes services by implementing automated monitoring scripts and self-healing infrastructure protocols. I was responsible for incident response management, performing post-mortem root cause analyses, and developing internal tools to streamline the deployment of high-performance droplets. My efforts significantly reduced manual intervention during scaling events and improved the overall resilience of the platform's networking layer for global users.",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T00:00:00Z",
  },
];

export const MOCK_EDUCATION: Education[] = [
  {
    id: 1,
    userId: 1,
    username: "alex_dev",
    institution: "MIT",
    degree: "Masters",
    fieldOfStudy: "Computer Science",
    startDate: "2016-09-01",
    endDate: "2018-05-01",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 2,
    userId: 1,
    username: "alex_dev",
    institution: "Stanford",
    degree: "Bachelors",
    fieldOfStudy: "Electrical Engineering",
    startDate: "2012-09-01",
    endDate: "2016-05-01",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 3,
    userId: 2,
    username: "beatrice_j",
    institution: "RISD",
    degree: "BFA",
    fieldOfStudy: "Graphic Design",
    startDate: "2014-09-01",
    endDate: "2018-05-01",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-02",
  },
  {
    id: 4,
    userId: 2,
    username: "beatrice_j",
    institution: "Y-Combinator",
    degree: "Founder Track",
    fieldOfStudy: "Business Strategy",
    startDate: "2019-06-01",
    endDate: "2019-09-01",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-02",
  },
  {
    id: 5,
    userId: 3,
    username: "charlie_data",
    institution: "UC Berkeley",
    degree: "PhD",
    fieldOfStudy: "Statistics",
    startDate: "2014-09-01",
    endDate: "2019-05-01",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-03",
  },
  {
    id: 6,
    userId: 3,
    username: "charlie_data",
    institution: "UCLA",
    degree: "BS",
    fieldOfStudy: "Mathematics",
    startDate: "2010-09-01",
    endDate: "2014-05-01",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-03",
  },
  {
    id: 7,
    userId: 4,
    username: "dana_ops",
    institution: "Georgia Tech",
    degree: "MS",
    fieldOfStudy: "Cybersecurity",
    startDate: "2018-09-01",
    endDate: "2020-05-01",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-04",
  },
  {
    id: 8,
    userId: 4,
    username: "dana_ops",
    institution: "Purdue University",
    degree: "BS",
    fieldOfStudy: "Information Technology",
    startDate: "2014-09-01",
    endDate: "2018-05-01",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-04",
  },
];

export const MOCK_SKILL_CATEGORIES = [
  {
    id: 1,
    userId: 1,
    username: "alex_dev",
    category: "Frontend",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 2,
    userId: 1,
    username: "alex_dev",
    category: "Backend",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 3,
    userId: 2,
    username: "beatrice_j",
    category: "Design Tools",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-02",
  },
  {
    id: 4,
    userId: 3,
    username: "charlie_data",
    category: "Data Science",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-03",
  },
  {
    id: 5,
    userId: 4,
    username: "dana_ops",
    category: "Cloud & Devops",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-04",
  },
];
